# 这个是调试时用的docker-compose.yml文件
version: '2'
services:
  web:
    image: rockchin/chatphp-base:latest
    container_name: chatphp-base
    volumes:
      - ./:/app/public/
    environment:
      - TZ=Asia/Shanghai
      - OPENAI_API_KEY=<your openai api key>
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=abc123
      - MYSQL_DATABASE=app
    ports:
      - "80:80"
      - "13306:3306"
